dataset_manifest:
  - data/droid_100_minimal/preprocessed/shards/manifest.jsonl
dataset_weighting:
  - 1.0
dataset_modality:
  - robotics
val_dataset_manifest: []
val_dataset_weighting: []

allow_multiple_epochs: true
num_workers: 0
prefetch_factor: 4
seq_len: 2048
shuffle: true
shuffle_buffer_size: 2000
shuffle_initial: 500
use_hf_fast_tokenizer: true
hf_fast_tokenizers_parallelism: true
hf_fast_tokenizer_rayon_threads: null
dataloader_in_order: false

dataset_cache:
  enabled: false
  cache_dir: null
  cache_size_gb: null
  cache_verbose: null

seed: 42

dataset_statistics:
  - /teamspace/studios/this_studio/vla_foundry/tutorials/data/droid_100_minimal/preprocessed/shards/stats.json
val_dataset_statistics: []

processor: simple_vlm
processor_kwargs: {}

img_num_tokens: 64
image_size: 512
max_text_seq_len: null

language_instruction_types:
  - original

camera_names:
  - exterior_image_1_left
  - exterior_image_2_left
  - wrist_image_left

image_indices:
  - -1
  - 0

image_names:
  - exterior_image_1_left_t-1
  - exterior_image_2_left_t-1
  - wrist_image_left_t-1
  - exterior_image_1_left_t0
  - exterior_image_2_left_t0
  - wrist_image_left_t0

pad_missing_images: false
mask_padded_images: false

proprioception_fields:
  - observation.state

tactile_fields: []

action_fields:
  - action

pose_groups: []
intrinsics_fields: []
extrinsics_fields: []

use_point_cloud: false
point_cloud_num_points: 4096

normalization:
  enabled: true
  method: std
  scope: global
  epsilon: 1.0e-08
  include_fields:
    - observation.state
    - action
  centered_norm: true
  field_configs:
    observation.state:
      method: std
      scope: global
      epsilon: 1.0e-08
      enabled: true
    action:
      method: std
      scope: global
      epsilon: 1.0e-08
      enabled: true
  lowdim_past_timesteps: 5
  lowdim_future_timesteps: 20

augmentation:
  enabled: true
  image:
    color_jitter:
      enabled: false
      brightness: 0.2
      contrast: 0.4
      saturation: 0.2
      hue:
        - -0.05
        - 0.05
    crop:
      enabled: false
      shape:
        - 224
        - 224
      mode: random

lowdim_past_timesteps: 2
lowdim_future_timesteps: 14
action_dim: 7
proprioception_dim: 7